basic_app/urls.py
from django.conf.urls import url
from django.urls import path
from django.contrib.auth import views as auth_views
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    path('', views.NewsListView.as_view(), name='news'),
    path('counter/<pk>/',views.NewCounterRedirectView.as_view(), name='new_counter')
]

content_project01/urls.py
from django.contrib import admin
from django.urls import path
from basic_app import views
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("basic_app.urls", namespace="basic_app")),
]

basic_app/models.py
from django.db import models

# Create your models here.

class News(models.Model):
    source_web = models.CharField(max_length=100)
    title = models.CharField(max_length=300)
    creation_time = models.DateTimeField()
    url = models.CharField(max_length=400)
    clicks_counter = models.IntegerField(default=0)
    status = models.BooleanField(default=True)

    def __str__(self):
        return self.source_web + '_' + str(self.creation_time)

    def update_counter(self):
        self.clicks_counter += 1
        self.save()

basic_app/views.py
from django.shortcuts import get_object_or_404
from django.views.generic import ListView
from basic_app.models import News
from django.views.generic.base import RedirectView

# Create your views here.

class NewsListView(ListView):
    '''List all news in inverse chronological order'''
    model = News
    paginate_by = 10
    template_name = 'home.html'

    def get_queryset(self):
        return News.objects.order_by('-creation_time')


class NewCounterRedirectView(RedirectView):
    '''Manage the redirection for counting the clicks'''
    permanent = False
    query_string = True

    def get_redirect_url(self, *args, **kwargs):
        single_new = get_object_or_404(News, pk=kwargs['pk'])
        single_new.update_counter()
        return single_new.url

basic_app/templates/home.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-uWxY/CJNBR+1zjPWmfnSnVxwRheevXITnMqoEIeG1LJrdI0GlVs/9cVSyPYXdcSF" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-kQtW33rZJAHjgefvhyyzcGF3C5TFyBQBA13V1RKPf4uH+bwyzQxZ6CmMZHmNBEfJ" crossorigin="anonymous"></script>
    <title>LATEST NEWS</title>
  </head>
  <body>    
    {% load tz %}
    <nav class="navbar navbar-dark bg-primary">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">LATEST NEWS!!!!</a>
      </div>
    </nav>
    
    <br>

    <h3>Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</h3>
    
    <br>

    <ul>
      {% for new in page_obj %}
        <li><a href="{% url 'basic_app:new_counter' pk=new.pk %}" target="_blank" rel="noopener noreferrer">{{ new.title }}</a></li>
        {{ new.source_web }}, {{ new.creation_time|localtime }}
      {% endfor %}
    </ul>

    <br>
    
    <nav aria-label="Page navigation example">
      <ul class="pagination">
        {% if page_obj.has_previous %}
          <li class="page-item"><a class="page-link" href="?page=1">First</a></li>
          <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
        {% else %}
          <li class="page-item disabled"><a class="page-link" href="#">First</a></li>
          <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
        {% endif %}
        {% if page_obj.has_next %}
          <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
          <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last</a></li>
        {% else %}
          <li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
          <li class="page-item disabled"><a class="page-link" href="#">Last</a></li>
        {% endif %}
      </ul>
    </nav>


  </body>
</html>